/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dam108t3_pooavanzada;

import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Doval
 */
public class dam108t3e02 extends javax.swing.JFrame {

    /**
     * Creates new form dam108t3e02
     */
    public dam108t3e02() {
        initComponents();
        DefaultComboBoxModel combo;
        combo = new DefaultComboBoxModel();
        
        for (Madera ma : Madera.values()) {
            combo.addElement(ma);
        }

        jComboBox_Maderas.setModel(combo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Ancho = new javax.swing.JLabel();
        jLabel_Alto = new javax.swing.JLabel();
        jLabel_TipoMadera = new javax.swing.JLabel();
        jLabel_Caja25m2 = new javax.swing.JLabel();
        jLabel_CajasTotal = new javax.swing.JLabel();
        jLabel_Importe = new javax.swing.JLabel();
        jText_Ancho = new javax.swing.JTextField();
        jText_Alto = new javax.swing.JTextField();
        jText_TotalCajas = new javax.swing.JTextField();
        jText_Importe = new javax.swing.JTextField();
        jButton_Calcular = new javax.swing.JButton();
        jComboBox_Maderas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_Ancho.setText("Ancho:");

        jLabel_Alto.setText("Alto:");

        jLabel_TipoMadera.setText("Tipo de Madera:");

        jLabel_Caja25m2.setText("Caja de 2.5 m2:");

        jLabel_CajasTotal.setText("Cajas a comprar:");

        jLabel_Importe.setText("Importe a pagar:");

        jButton_Calcular.setText("Calcular");
        jButton_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CalcularActionPerformed(evt);
            }
        });

        jComboBox_Maderas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Ancho)
                    .addComponent(jLabel_Alto)
                    .addComponent(jLabel_Caja25m2)
                    .addComponent(jLabel_CajasTotal)
                    .addComponent(jLabel_Importe)
                    .addComponent(jLabel_TipoMadera))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jText_Importe, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(jText_TotalCajas, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(jText_Alto, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(jText_Ancho)
                    .addComponent(jButton_Calcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_Maderas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_Ancho)
                    .addComponent(jText_Ancho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Alto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jText_Alto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_TipoMadera)
                    .addComponent(jComboBox_Maderas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_Caja25m2)
                    .addComponent(jButton_Calcular))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_CajasTotal)
                            .addComponent(jText_TotalCajas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(jLabel_Importe))
                    .addComponent(jText_Importe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CalcularActionPerformed
        int alto, ancho, precio, cajas;
        alto = Integer.parseInt(jText_Alto.getText());
        ancho = Integer.parseInt(jText_Ancho.getText());
        cajas = madera.calcularCajas(alto, ancho);
        precio = madera.calcularPrecio((Madera)jComboBox_Maderas.getSelectedItem(), cajas);
        jText_TotalCajas.setText(String.valueOf(cajas));
        jText_Importe.setText(String.valueOf(precio));
    }//GEN-LAST:event_jButton_CalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dam108t3e02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dam108t3e02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dam108t3e02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dam108t3e02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dam108t3e02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Calcular;
    private javax.swing.JComboBox<String> jComboBox_Maderas;
    private javax.swing.JLabel jLabel_Alto;
    private javax.swing.JLabel jLabel_Ancho;
    private javax.swing.JLabel jLabel_Caja25m2;
    private javax.swing.JLabel jLabel_CajasTotal;
    private javax.swing.JLabel jLabel_Importe;
    private javax.swing.JLabel jLabel_TipoMadera;
    private javax.swing.JTextField jText_Alto;
    private javax.swing.JTextField jText_Ancho;
    private javax.swing.JTextField jText_Importe;
    private javax.swing.JTextField jText_TotalCajas;
    // End of variables declaration//GEN-END:variables
    Madera madera = Madera.BAMBU;
}
